### ISSUE TITLE
getting error "Can not establish connection" with the node js agent when using ssl for server

### ISSUE THREAD

**Issue by dukie66** [jianghengle/traceroute-map#11]
Making the request from client with 
`wss://`
But getting error
Agent and client has ssl. 
When using without ssl and making request from client with `ws://` to the agent no errors are coming. 
Does the server always have to be in http.

**Comment by jianghengle** [comment]
The node js agent uses [ws package](https://www.npmjs.com/package/ws) to implement websocket server. If you want `wss://` you should update [the agent code](https://github.com/jianghengle/traceroute-map/blob/master/agent/nodejs/agent.js) following [this example](https://www.npmjs.com/package/ws#user-content-external-https-server). You also need to update [the client code](https://github.com/jianghengle/traceroute-map/blob/master/client/src/components/Traceroute.vue#L259) to connect to your `wss://` agent.
